apiVersion: v1
kind: Pod
metadata:
  name: nginx-k8s
  labels:
    name: nginx-k8s
  annotations:
    desc: "This is a nginx pod created as example"
spec:
  containers:
    - name: nginx-k8s
      image: nginx:stable
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "1000m"
          memory: "254Mi"
